services:
  app:
    build: .
    container_name: pansea-backend
    env_file:
      - .env
    environment:
      # Ensure critical defaults if missing in .env
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-false}
      PORT: ${PORT:-8000}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    command: >-
      sh -c "exec gunicorn -k uvicorn.workers.UvicornWorker --workers 2 --threads 2 --access-logfile - --timeout 30 --graceful-timeout 20 --limit-request-line 16384 --limit-request-field_size 16384 app.main:app"


