"""rename_audio_to_lesson_and_add_lesson_summary_relationship

Revision ID: 2ac8ba3a6fc4
Revises: 3b27f36b85e4
Create Date: 2025-09-07 14:59:14.882032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ac8ba3a6fc4'
down_revision: Union[str, Sequence[str], None] = '3b27f36b85e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the audio table to lessons to preserve data
    op.rename_table('audio', 'lessons')
    
    # Rename the indexes to match the new table name
    op.drop_index(op.f('ix_audio_class_id'), table_name='lessons')
    op.drop_index(op.f('ix_audio_s3_key'), table_name='lessons')
    op.create_index(op.f('ix_lessons_class_id'), 'lessons', ['class_id'], unique=False)
    op.create_index(op.f('ix_lessons_s3_key'), 'lessons', ['s3_key'], unique=True)
    
    # Add lesson_id column to lectures_summaries table
    op.add_column('lectures_summaries', sa.Column('lesson_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lectures_summaries', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key and lesson_id column
    op.drop_constraint(None, 'lectures_summaries', type_='foreignkey')
    op.drop_column('lectures_summaries', 'lesson_id')
    
    # Rename the lessons table back to audio
    op.rename_table('lessons', 'audio')
    
    # Rename the indexes back to match the audio table name
    op.drop_index(op.f('ix_lessons_class_id'), table_name='audio')
    op.drop_index(op.f('ix_lessons_s3_key'), table_name='audio')
    op.create_index(op.f('ix_audio_class_id'), 'audio', ['class_id'], unique=False)
    op.create_index(op.f('ix_audio_s3_key'), 'audio', ['s3_key'], unique=True)
    # ### end Alembic commands ###
