"""rename_lectures_summaries_to_lesson_summaries

Revision ID: 931c31238dcb
Revises: 2ac8ba3a6fc4
Create Date: 2025-09-07 15:33:50.701919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '931c31238dcb'
down_revision: Union[str, Sequence[str], None] = '2ac8ba3a6fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the lectures_summaries table to lesson_summaries to preserve data
    op.rename_table('lectures_summaries', 'lesson_summaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the lesson_summaries table back to lectures_summaries
    op.rename_table('lesson_summaries', 'lectures_summaries')
    # ### end Alembic commands ###
