#!/bin/bash
# Setup script for Google Speech-to-Text integration

echo "Google Speech-to-Text Setup Instructions:"
echo "========================================="
echo ""
echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
echo "2. Enable the Speech-to-Text API for your project"
echo "3. Create a service account:"
echo "   - Go to IAM & Admin → Service Accounts"
echo "   - Click 'Create Service Account'"
echo "   - Name: 'speech-to-text-service'"
echo "   - Role: 'Cloud Speech-to-Text API User'"
echo "   - Download the JSON key file"
echo ""
echo "4. Place the JSON file in your whisper-service project:"
echo "   Example: /Users/thun/Desktop/pan-sea/whisper-service/gcloud-key.json"
echo ""
echo "5. Set environment variables (add to your .env file):"
echo "   export GOOGLE_APPLICATION_CREDENTIALS='/path/to/your/gcloud-key.json'"
echo "   export USE_GOOGLE_STT=true"
echo "   export GOOGLE_STT_USE_ENHANCED=true"
echo "   export TRANSCRIPTION_SERVICE_URL=''"  # This forces Google STT instead of external service
echo ""
echo "6. Test the integration:"
echo "   python test_enhanced_transcription.py"
echo ""
echo "The enhanced transcription service will then provide real word-level timestamps"
echo "from Google Speech-to-Text instead of approximated ones."
