version: '3.8'

services:
  whisper-service:
    build: .
    ports:
      - "80:8000"
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WHISPER_MODEL_SIZE=tiny
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    volumes:
      - ./logs:/app/logs
      - ./white-fiber-470711-s7-efbed390336b.json:/app/google-credentials.json:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
